@startuml
object "<u>Nima:Instructor</u>" as nima {
    firstName = "Nima"
    lastName = " Davarpanah"
    officeNumber = "3-2636"
}

object "<u>CleanCode:Textbook</u>"  as cc{
    author = "Robert Cecil Martin"
    publisher = "Pearson"
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
}

object "<u>CS4800:Course</u>" as swe {
    name = "CS4800: Software Engineering"
}

swe -- nima
nima -- cc

@enduml