@startuml
'https://plantuml.com/object-diagram

object Instructor {
    firstName = "Nima"
    lastName = " Davarpanah"
    officeNumber = "3-2636"
}

object Textbook {
    author = "Robert Cecil Martin"
    publisher = "Pearson"
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
}

object Course

Course -- Instructor
Instructor -- Textbook

@enduml