@startuml
object "<u>php_demo1:Folder</u>" as php {
    setName = "php_demo1"
}
object "<u>SourceFiles:Folder</u>" as sf {
    addSubfolder = "Source Files"
}
object "<u>IncludePath:Folder</u>" as ip {
    addSubfolder  = "Include Path"
}
object "<u>RemoteFiles:Folder</u>" as rf {
    addSubfolder  = "Remote Files"
}
object "<u>.phalcon:Folder</u>" as phalcon {
    getSubfolder  = "Source Files"
    addSubfolder = ".phalcon"
}

object "<u>cache:Folder</u>" as cache{
    getSubfolder  = "Source Files"
    addSubfolder = "cache"
}
object  "<u>public:Folder</u>" as public {
    getSubfolder  = "Source Files"
    addSubfolder = "public"
}


object "<u>.htaccess:Files</u>" as hta {
    getSubfolder = "Source Files"
    getSubfolder = "public"
    addFile = ".htaccess"
}
object "<u>.htrouter:Files</u>" as htr {
    getSubfolder = "Source Files"
    getSubfolder = "public"
    addFile = ".htrouter.php"
}
object "<u>index:Files</u>" as index{
    getSubfolder = "Source Files"
    getSubfolder = "public"
    addFile = "index.html"
}

php -- sf
php -- ip
php -- rf
sf -- phalcon
sf -- cache
sf -- public
public -- hta
public -- htr
public -- index

@enduml
