@startuml

object "<u>titanic:Ship</u>" as ts {
    name = "Titanic"
    yearBuilt = "March31st,1909"
}

object "<u>MVGemini:Ship</u>" as mv  {
    name = "MVGemini"
    yearBuilt = "May30th,1991"
}

object "<u>MVGemini:CruiseShip</u>" as cruise {
    maxNumberPassengers = 100
}

object  "<u>EverGiven:Ship</u>" as eg {
       name = "EverGiven"
       yearBuilt = "September25th,2018"
}

object "<u>EverGiven:CargoShip</u>" as cargo {
    cargoCapacityInTonnage = 220940
}


mv -- cruise
eg -- cargo
@enduml
